name: Docker Base Image Build & Publish

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

    paths:
      - 'docker/base/**'
      - 'docker/custom/**'
      - '.github/workflows/docker-publish.yml'

env:
  DOCKER_BUILDKIT: 1
  BASE_IMAGE_NAME: gpack-base
  BASE_DOCKER_FILE: docker/base/Dockerfile
  CUSTOM_IMAGE_NAME: gpack-custom
  CUSTOM_DOCKER_FILE: docker/custom/Dockerfile
  RELEASE_VERSION: 0.0.1

jobs:
  # Build & Run tests.
  # base-build-test:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Base Image Build and Tests
  #       run: |
  #           # build base image
  #           docker build . --file $BASE_DOCKER_FILE --tag $BASE_IMAGE_NAME

  #           # test base image
  #           docker run $BASE_IMAGE_NAME echo "TEST ECHO: test base docker image"

  # Push base image to GitHub Packages.
  base-push:
    # Ensure test job passes before pushing image.
    # needs: base-build-test

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: $BASE_DOCKER_FILE
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.BASE_IMAGE_NAME }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ env.BASE_IMAGE_NAME }}:$RELEASE_VERSION

  # Push custom image to GitHub Packages.
  custom-push:
    # Ensure test job passes before pushing image.
    needs: base-push

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: $CUSTOM_DOCKER_FILE
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.CUSTOM_IMAGE_NAME }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ env.CUSTOM_IMAGE_NAME }}:$RELEASE_VERSION

